### ISSUE TITLE
Исследовательская часть

### ISSUE THREAD

**Issue by v1lge** [v1lge/cafe_bd#4]
[Исследовательская часть 2.pdf](https://github.com/v1lge/cafe_bd/files/11038792/2.pdf)

**Comment by wldmr-key** [comment]
Для начала тебе следует разобраться с тем, что такое концептуальная схема и сделать согласованными описание предметной области, требований к системе и концептуальную схему

**Comment by v1lge** [comment]
1. Постановка задачи проектирования
Задача курсовой работы состоит в разработке автоматизированной системы управления работой кафе. Необходимо автоматизировать основные процессы ресторанного бизнеса, связать отдельные аспекты работы в единую систему, разработать удобный пользовательский интерфейс для работы с программой, обеспечить логичность и целостность БД. 
        
 

2. Описание предметной области
       Кафе – это предприятие общественного питания и  отдыха. Меню такого предприятия содержит напитки, закуски и блюда разных типов. У всех сотрудников есть своя должность. К основным должностям ресторанного бизнеса можно отнести официантов, кассиров, управляющих, работников кухни, барменов. Каждый заказ закреплен за конкретным официантом. В заказе посетителя содержатся различные пункты меню. В меню указано наименование блюда, ингредиенты блюда, цена, вес, может быть указана и пищевая ценность каждого блюда. Соответственно, каждый заказ должен содержать информацию, о том, кто его обрабатывает, какие блюда или напитки заказаны, их количество, цена, дата и определенные замечания к заказу.
Руководство кафе может быть заинтересовано в автоматизации таких моментов, как:
	оформление заказов; 
	добавление новых блюд и удаление блюд, которые не пользуются популярностью; 
	подсчёт итоговой суммы каждого заказа; 
	добавление и удаление информации об официантах в случаях увольнения и принятия на работу новых сотрудников; 
	формирование отчётности; 
	ведение информации о блюдах в меню.
Автоматизация рабочих процессов позволит управлять процессами внутри заведения общественного питания. Установка такой системы дает возможность распределять и минимизировать расходы, контролировать персонал, улучшать сервис, эффективно работать с меню и т. д.

 3. Анализ аналогов и прототипов
Во ходе проектирования были проанализированы некоторые похожие системы.
	Система R-Keeper

Система R-Keeper (разработка московской фирмы UCS, которая работает на рынке с 1992 г.) является самой совершенной по своим функциональным возможностям, что признают даже продавцы программ-конкурентов. На сегодняшний день она автоматизации установлена почти в 6000 ресторанов. Среди них не только российские предприятия, но и иностранные, например, турецкие, болгарские, австрийские и испанские.
Задумана система R-Keeper как мощный инструмент для всеобъемлющего контроля зала, складского учета и учета рабочего времени. чЭто отличный помощник для собственников в сфере финансового менеджмента, т. е. для управления ресторанным бизнесом.
	Система TillyPad
TillyPad — это комплекс автоматизации, предназначенный для клубов, ресторанов, баров, казино, фитнес-клубов, кинотеатров и прочих предприятий индустрии развлечений.
Появлению TillyPad в 1995 г. предшествовало глобальное маркетинговое исследование, в ходе которого был выявлен наиболее привлекательный и активно развивающийся сегмент рынка — ресторанный бизнес и индустрия развлечений. Проанализировав ситуацию в данном сегменте, специалисты создали систему, которая отвечает всем задачам, стоящим перед владельцами бизнеса сферы развлечений, и одновременно решает характерные для этой области актуальные проблемы — пресечение злоупотреблений персонала, возможность введения широкой системы скидок, планирование маркетинговых акций, управление в реальном времени и т. д.
Уникальность TillyPad состоит в том, что он не скопирован с западных аналогов, долгое время существующих на рынке. Это продукт, который с начала и до конца разработан российскими специалистами. Соответственно, в нем была учтена вся специфика российского ведения бизнеса и расставлены нужные акценты.

Кроме того, разработчики TillyPad с самого начала ставили своей целью не просто предложить ответ на существующие требования, но заложить в систему механизмы, которые позволят оперативно реагировать на изменения, постоянно возникающие по мере развития бизнеса.
	АСЮР:Ресторан
АСТОР:Ресторан — это отраслевое решение компании «АСТОР ВЦ», которое используют в повседневной деятельности более 700 отечественных предприятий индустрии питания.
Программное обеспечение «АСТОР:Ресторан» применяют в сетевом бизнесе, поскольку оно наиболее адекватно отвечает запросам рынка. Данный программный продукт предоставляет возможность владельцу сети заведений создавать индивидуальную концепцию управления, сбалансированно сочетающую элементы централизованного и децентрализованного менеджмента.
Централизованный менеджмент обязательно предполагает выделение центрального офиса, проводящего общую политику формирования меню, ценообразования в отдельных ресторанах сети, а также системы скидок. Именно центр занимается взаиморасчетами с поставщиками и закупкой товаров (за исключением скоропортящихся) через общий склад-распределитель. В центральном офисе производятся также обобщение и обработка данных о работе каждого из ресторанов, создание консолидированных отчетов. На местах менеджеры ведут работу с покупателями, контролируют деятельность персонала и соблюдение технологий работы.
4. Перечень задач, подлежащих решению в процессе разработки

        Задачи, подлежащие решению в процессе разработки, следующие:
•	Выполнить анализ предметной области
•	Проанализировать аналоги
•	Создать прототип интерфейса
•	Спроектировать концептуальную схему данных
•	Выбрать инструменты для разработки
•	Изучить выбранные инструменты
•	Разработать систему 
•	Обработать ошибочные ситуации
•	Оформить документацию к проекту

 5. Требования к системе
Разрабатываемый программный продукт должен соблюдать следующие требования: 
•	Должны быть отображены все необходимые данные о сотрудниках.
•	Должен быть предусмотрен список заказов, где имеется информация о самом заказе, а также указан сотрудник, который обрабатывает этот заказ.
•	Для каждого заказа должна быть автоматически подсчитана общая сумма заказа, а также процент от выручки, который получает обрабатывающий его сотрудник.
•	Возможность редактирования меню.
•	Возможность добавлять и удалять ингредиенты блюд, а также редактировать информацию о ингредиенте.
•	Предотвращение ошибочных ситуаций пользователя.
•	Предоставление данных в виде отчета.

**Comment by v1lge** [comment]
![image](https://user-images.githubusercontent.com/36515204/227706784-a0f0b17c-0524-4f0e-a7c8-3942578ebb89.png)

**Comment by wldmr-key** [comment]
я не нашел в описании предметной области и требованиях к системе никаких кодов, которые есть в концептуальной схеме. Процент от выручки упоминается в контексте заказа, а на схеме он в должности - почему? Значительное количество атрибутов в описнаии не упомянуто

**Comment by v1lge** [comment]
Внес изменения в описание и требования к системе.

2.2 Описание предметной области
       Кафе – это предприятие общественного питания и  отдыха. Меню такого предприятия содержит напитки, закуски и блюда разных типов. У всех сотрудников есть своя должность. К основным должностям ресторанного бизнеса можно отнести официантов, кассиров, управляющих, работников кухни, барменов. Для каждой должности учитывается оклад, а также процент от выручки для работника. Сотрудник предприятия должен предоставить свои личные данные (ФИО, номер телефона, адрес проживания, дата рождения). У работодателя имеется фотография каждого сотрудника и дата принятия этого сотрудника на работу.  Каждый заказ закреплен за конкретным официантом. В заказе посетителя содержатся различные пункты меню. В меню указано наименование блюда, ингредиенты блюда, цена, вес, может быть указана и пищевая ценность каждого блюда. Соответственно, каждый заказ должен содержать информацию, о том, кто его обрабатывает, какие блюда или напитки заказаны, их количество, цена, дата и определенные замечания к заказу. Для каждого объекта предусмотрен уникальный код, который позволяет идентифицировать этот объект.
Руководство кафе может быть заинтересовано в автоматизации таких моментов, как:

- 	оформление заказов; 
- 	добавление новых блюд и удаление блюд, которые не пользуются популярностью; 
- 	подсчёт итоговой суммы каждого заказа; 
- 	добавление и удаление информации об официантах в случаях уволь-нения и принятия на работу новых сотрудников; 
- 	формирование отчётности; 
- 	ведение информации о блюдах в меню.

Автоматизация рабочих процессов позволит управлять процессами внутри заведения общественного питания. Установка такой системы дает возможность распределять и минимизировать расходы, контролировать персонал, улучшать сервис, эффективно работать с меню и т. д.


2.5 Требования к системе
Разрабатываемый программный продукт должен соблюдать следующие требования: 
•	Должны быть отображены все необходимые данные о сотрудниках.
•	Должен быть предусмотрен список заказов, где имеется информация о самом заказе, а также указан сотрудник, который обрабатывает этот заказ.
•	За каждой должностью должен быть закреплен определенный оклад, а также процент, который сотрудник получает от выручки.
•	Возможность редактирования меню.
•	Возможность добавлять и удалять ингредиенты блюд, а также редактировать информацию о ингредиенте.
•	Предотвращение ошибочных ситуаций пользователя.
•	Предоставление данных в виде отчета.
