### ISSUE TITLE
Проектно- Технологическая часть

### ISSUE THREAD

**Issue by v1lge** [v1lge/cafe_bd#5]
[Проектно- Технологическая часть.pdf](https://github.com/v1lge/cafe_bd/files/11026877/-.pdf)

**Comment by v1lge** [comment]
![image](https://user-images.githubusercontent.com/36515204/228200210-e19ae5b3-75f6-4427-90eb-dddab83535b7.png)
![image](https://user-images.githubusercontent.com/36515204/228201747-9b1ed5da-b126-48c4-859a-ebddb6782351.png)
![image](https://user-images.githubusercontent.com/36515204/228201816-d956de9b-2e82-47ca-9836-567de565f112.png)
![image](https://user-images.githubusercontent.com/36515204/228201892-b69de30c-2aa5-46b1-8473-a7b34db75035.png)
![image](https://user-images.githubusercontent.com/36515204/228201964-2b89b3a3-0c07-4b02-89d3-bf1c25900d31.png)
![image](https://user-images.githubusercontent.com/36515204/228202012-049064a3-d900-49ee-998b-2f67eb23dd43.png)

**Comment by wldmr-key** [comment]
прокатит для твоего случая
