### ISSUE TITLE
Проектно - конструкторская часть

### ISSUE THREAD

**Issue by v1lge** [v1lge/cafe_bd#6]
[ПРОЕКТНО-КОНСТРУКТОРСКАЯ ЧАСТЬ.pdf](https://github.com/v1lge/cafe_bd/files/11055267/-.pdf)

**Comment by v1lge** [comment]
3.1  Реализация приложения
Для работы с БД, была использована СУБД Microsoft Sql Server 2016. Для разработки была выбрана среда Microsoft Visual Studio и язык C#. Для создания интерфейса были использованы Windows Forms.
         

 



3.2 Разработка структуры приложения 
Для решения поставленных задач было принято следующее решение по инструментам разработки проекта: 
Для организации доступа к данным было решено использовать объектно-ориентированную технологию для работы с данными Entity Framework (EF) платформы .NET. EF значительно упрощает доступ к данным, избавляет разработчика от необходимости написания связанной с этим части кода, насыщенную SQL-запросами. 
EF позволяет взаимодействовать с реляционными базами данных, не имея дела с кодом SQL: исполняющая среда EF генерирует подходящие операторы SQL, когда разработчик применяет LINQ-запросы к строго типизированным классам. Такие строго типизированные классы называются сущностями. Сущности - это концептуальная модель (модель сущностных данных, EDM - Entity Data Model) физической базы данных, которая отображается на предметную область. EDM представляет собой набор классов клиентской стороны, которые отображаются на физическую базу данных. Однако сущности не обязаны напрямую отображаться на схему базы данных - сущностные классы можно реструктурировать для соответствия существующим потребностям, и исполняющая среда EF отобразит эти уникальные имена на конкретную схему. 


 
Рисунок 3.1 – Упрощённое представление схемы обращения к данным с помощью EF

Технология EF предлагает следующие способы взаимодействия с базой данных:
1.	Database First: Entity Framework создаёт набор классов, которые отражают модель конкретной существующей базы данных.
2.	Model First: сначала разработчик создаёт модель базы данных, по которой затем Entity Framework создаёт реальную базу данных на сервере.
3.	Code First: разработчик создаёт класс модели данных, которые будут храниться в БД, а затем Entity Framework по этой модели генерирует базу данных и её таблицы.
Так уже имеется разработанная база данных, был выбран способ Database First. Генерация *.edmx файла даёт в результате сущностные классы, которые отображаются на таблицы БД, и класс, расширяющий DbContext из System.Data.Entity. Этот класс используется для запросов из БД и группировки вносимых изменений, которые будут добавлены в хранилище как единое целое. 
Все запросы к базе данных с помощью класса DbContext инкапсулированы в классе Repository.cs. 

 
Рисунок 3.2 - Схема классов Repository инкапсулирующих логику работы с БД

В качестве примера можно расммотреть метод AddEntity() класса Repository для добавления новой сущности в БД. Сигнатура метода является одинаковой для классов приложения пользователя и сотрудника.

        /// <summary>
        /// Метод добавления сущности в БД
        /// </summary>
        public T AddEntity<T>(T entity) where T : class
        {
            using (var context = new HelpDeskDBEntities())
            {
                var adedEntity = context.Set<T>().Add(entity);
                context.SaveChanges();
                return adedEntity;
            }
     }
Листинг 2.1 – Код метода добавления новой сущности в БД
С помощью сгенерированного моделью EF класса, метод добавляет новую сущность в БД и возвращает ссылку на добавленный объект (объект возвращается с уникальным ID, сгенерированным сервером). В аналогичной манере реализованы остальные методы класса Repository для добавления, удаления и обновления данных в БД.

**Comment by v1lge** [comment]
![image](https://user-images.githubusercontent.com/36515204/227706882-5bad1a0c-0701-4be6-9b15-f1f63e52634b.png)

**Comment by wldmr-key** [comment]
что за странная нотация для схемы? ты требования к оформлению ПЗ читал? Как насчет реакции на вопрос на консультации - что происходит, когда цена блюда изменяется?

**Comment by v1lge** [comment]
![физич схема испр](https://user-images.githubusercontent.com/36515204/227925399-6c98fa85-5f41-4f6d-a9f8-9cc0ff23fbee.png)

**Comment by v1lge** [comment]
Ну на данный момент, при изменении цены блюда изменится и сумма заказа..

**Comment by v1lge** [comment]
Дописал здесь.

3.2 Разработка структуры приложения 
Для решения поставленных задач было принято следующее решение по инструментам разработки проекта: 
Для организации доступа к данным было решено использовать объектно-ориентированную технологию для работы с данными Entity Framework (EF) платформы .NET. EF значительно упрощает доступ к данным, избавляет разработчика от необходимости написания связанной с этим части кода, насыщенную SQL-запросами. 
EF позволяет взаимодействовать с реляционными базами данных, не имея дела с кодом SQL: исполняющая среда EF генерирует подходящие операторы SQL, когда разработчик применяет LINQ-запросы к строго типизированным классам. Такие строго типизированные классы называются сущностями. Сущности - это концептуальная модель (модель сущностных данных, EDM - Entity Data Model) физической базы данных, которая отображается на предметную область. EDM представляет собой набор классов клиентской стороны, которые отображаются на физическую базу данных. Однако сущности не обязаны напрямую отображаться на схему базы данных - сущностные классы можно реструктурировать для соответствия существующим потребностям, и исполняющая среда EF отобразит эти уникальные имена на конкретную схему. 


 
Рисунок 3.1 – Упрощённое представление схемы обращения к данным с помощью EF

Технология EF предлагает следующие способы взаимодействия с базой данных:
1.	Database First: Entity Framework создаёт набор классов, которые отражают модель конкретной существующей базы данных.
2.	Model First: сначала разработчик создаёт модель базы данных, по которой затем Entity Framework создаёт реальную базу данных на сервере.
3.	Code First: разработчик создаёт класс модели данных, которые будут храниться в БД, а затем Entity Framework по этой модели генерирует базу данных и её таблицы.
Так уже имеется разработанная база данных, был выбран способ Database First. Генерация *.edmx файла даёт в результате сущностные классы, которые отображаются на таблицы БД, и класс, расширяющий DbContext из System.Data.Entity. Этот класс используется для запросов из БД и группировки вносимых изменений, которые будут добавлены в хранилище как единое целое. 
Все запросы к базе данных с помощью класса DbContext инкапсулированы в классе Repository.cs. 

 
Рисунок 3.2 - Схема классов Repository инкапсулирующих логику работы с БД

В качестве примера можно расммотреть метод AddEntity() класса Repository для добавления новой сущности в БД. Сигнатура метода является одинаковой для классов приложения пользователя и сотрудника.

        /// <summary>
        /// Метод добавления сущности в БД
        /// </summary>
        public T AddEntity<T>(T entity) where T : class
        {
            using (var context = new HelpDeskDBEntities())
            {
                var adedEntity = context.Set<T>().Add(entity);
                context.SaveChanges();
                return adedEntity;
            }
     }
Листинг 2.1 – Код метода добавления новой сущности в БД
С помощью сгенерированного моделью EF класса, метод добавляет новую сущность в БД и возвращает ссылку на добавленный объект (объект возвращается с уникальным ID, сгенерированным сервером). В аналогичной манере реализованы остальные методы класса Repository для добавления, удаления и обновления данных в БД.

Ключевым компонентом работы приложения является работа с заказами. В разделе заказов будет предоставлена вся хранящаяся в БД информация о проведенных заказах. В процессе создания заказа выбирается сотрудник, который его обрабатывает, а также будет выбрана текущая дата. Сумма заказа будет зависеть от текущих цен блюд, а также их количества. Соответственно, при изменении цены блюда, изменится и сумма заказа. Процент, который получит сотрудник от выручки зависит от его должности. В разделе заказов, заказы можно редактировать или удалять.

**Comment by wldmr-key** [comment]
страх и ужас
хрен с ней с курсовой, на сам-то, хоть, понимаешь, какая несуразная модель работы реального ресторана получилась?

**Comment by v1lge** [comment]
сейчас уже понимаю
