### ISSUE TITLE
РПЗ

### ISSUE THREAD

**Issue by v1lge** [v1lge/cafe_bd#8]
[РПЗ БД.pdf](https://github.com/v1lge/cafe_bd/files/11103335/default.pdf)

**Comment by wldmr-key** [comment]
у меня рука не поднимается поставить тебе  положительную оценку, поэтому, я отписал Евгению Владимировичу, чтобы он сделал это ))
Загружай все барахло в ЭОС, вклчая презентацию и графические материалы. Распечатывай и подходи к Евгению Владимировичу с направлением
За руководителя я в понедельник распишусь

**Comment by v1lge** [comment]
понял, спасибо
